baseURL: https://blog.madcodelife.me/
languageCode: zh-CN
title: Digital Notes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  description: Floyd Wang çš„åšå®¢
  author: Floyd Wang
  keywords: [blog, page, Floyd Wang, madcodelife, åšå®¢ï¼ŒæŠ€æœ¯ï¼Œåˆ†äº«]

  defaultTheme: auto
  env: production
  comments: true

  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowToc: true
  ShowShareButtons: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: ğŸ“’
    Content: >
      **æ•°å­—å¤‡å¿˜å½•**ï¼Œç”¨æ–‡å­—è®°å½•ä¸‹ä¸æˆç†Ÿçš„æƒ³æ³•ï¼Œç»“æœä¸é‡è¦ï¼Œé‡è¦çš„æ˜¯è¿‡ç¨‹ã€‚

  socialIcons:
    - name: github
      url: https://github.com/madcodelife
    - name: twitter
      url: https://twitter.com/choujiaojiao

  assets:
    disableHLJS: true
    favicon: https://res.cloudinary.com/dspnhl2nc/image/upload/v1678204485/favicon_qfqxw5.ico
    favicon16x16: https://res.cloudinary.com/dspnhl2nc/image/upload/v1678204485/favicon-16x16_nzxfzt.png
    favicon32x32: https://res.cloudinary.com/dspnhl2nc/image/upload/v1678204485/favicon-32x32_cthpjw.png
    apple_touch_icon: https://res.cloudinary.com/dspnhl2nc/image/upload/v1678204485/apple-touch-icon_uiiibk.png
    safari_pinned_tab: https://res.cloudinary.com/dspnhl2nc/image/upload/v1678204485/apple-touch-icon_uiiibk.png

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false

taxonomies:
  tag: tags
  category: categories

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3
