baseURL: https://blog.madcodelife.me/
languageCode: zh-CN
title: Digital Notes
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  comments: true
  env: production
  author: Floyd Wang

  ShowReadingTime: true
  ShowCodeCopyButtons: true
  ShowToc: true

  homeInfoParams:
    Title: ğŸ“’
    Content: >
      **æ•°å­—å¤‡å¿˜å½•**ï¼Œè®°æ€§ä¸å¥½ï¼Œç”¨æ–‡å­—è®°å½•ä¸‹ä¸æˆç†Ÿçš„æƒ³æ³•ï¼Œç»“æœä¸é‡è¦ï¼Œé‡è¦çš„æ˜¯è¿‡ç¨‹ã€‚

  socialIcons:
    - name: github
      url: https://github.com/madcodelife
    - name: twitter
      url: https://twitter.com/choujiaojiao

taxonomies:
  tag: tags
  category: categories

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3
